language: python

python:
  - "3.6"

install:
  - pip install pipenv
  - pipenv lock -r > requirements.txt
  - pip install -r requirements.txt

script:
  - make publish
  - touch output/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: output/
  repo: johnliu55tw/johnliu55tw.github.io
  target_branch: master
  on:
    branch: master
